---
services:
  idp:
    image: 300448126090.dkr.ecr.us-east-1.amazonaws.com/firespring/docker-simplesamlphp:${DST_TAG:-latest}
    build:
      context: .
      args:
        SIMPLESAMLPHP_VERSION: "1.19.9"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://app.example.com
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/test-sp
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/test-sp
      SIMPLESAMLPHP_IDP_ADMIN_PASSWORD: password123
      SIMPLESAMLPHP_IDP_SECRET_SALT: salt
